version: "3.8"
services:
  message-api:
    build:
      context: ./MessageApi
      dockerfile: Dockerfile

    container_name: Message-API
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_started

    environment:
      RABBITMQ_HOST: rabbitmq
      POSTGRES_DB: lab10
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5434

    ports:
      - "8000:8000"

    restart: "unless-stopped"
    command: [
      "python", "-m", "uvicorn",
      "application:app",
      "--host", "0.0.0.0",
      "--port", "8000"
    ]

  message-processor:
    build:
      context: ./MessageProcessor
      dockerfile: Dockerfile
    container_name: Message-Processor
    depends_on:
      message-api:
        condition: service_started
      rabbitmq:
        condition: service_healthy

    environment:
      RABBITMQ_HOST: rabbitmq

    command: ["python", "main.py"]
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

    restart: unless-stopped


  postgres:
    image: postgres:latest
    container_name: lab10-db
    environment:
      POSTGRES_DB: lab10
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    volumes:
      - lab10_postgres_data:/var/lib/postgresql/data
    networks:
      - lab10-network

    restart: unless-stopped

volumes:
  lab10_postgres_data:

networks:
  lab10-network:
    driver: bridge